### ISSUE TITLE
What is the difference between the different "Assets" available to download?

### ISSUE THREAD

**Issue by royachiron** [gibbed/Gibbed.BorderlandsOz#10]
Hi. Borderlands player, recently used your awesome code to improve my save (yay for sync gear level), was wondering what is the difference here
![image](https://user-images.githubusercontent.com/23020420/39962314-b69db9f4-5653-11e8-9f90-eeab5d333a9e.png)

Would you mind I make a readme for the repository? with some relevant info and links to the UCP and whatnot...

**Comment by gibbed** [comment]
Making a proper README is on my TODO list for sure.

The `borderlandsoz-*` is all tools built from the repository, whereas `saveedit-*` is specifically only the save editor. I intend to change the name of the general package to something more obvious in the future as well.
