### ISSUE TITLE
UNKNOWN APPLICATION

### ISSUE THREAD

**Issue by Cl4pD3rp** [gibbed/Gibbed.BorderlandsOz#14]
the application format is an unknown application ( Extention )

https://imgur.com/a/vX5kPfo

help fix

**Comment by gibbed** [comment]
You downloaded the source code instead of a binary release.

https://github.com/gibbed/Gibbed.BorderlandsOz/releases/latest

**Comment by Cl4pD3rp** [comment]
i nvr understand this stuff, srry for consuming ur time and thnx for the fast responce!
