### ISSUE TITLE
Skill Points is not added o change in the save file

### ISSUE THREAD

**Issue by cazartelli** [gibbed/Gibbed.BorderlandsOz#16]
Im loading the Pre sequel  save file .. y try to changue de skils points value .. but in the game de value is not change .

Help

**Comment by rdricco** [comment]
Still not working for me on 1.0.21.
Looks ok if I save the file and reopen but the points are not added ingame.

**Comment by gibbed** [comment]
Skill points are sanity checked in-game. You can't exceed what you're actually allowed to have per your character's level.
