### ISSUE TITLE
Interface unreadable in Win10 VM

### ISSUE THREAD

**Issue by themightyoarfish** [gibbed/Gibbed.BorderlandsOz#20]
I'm running this in a Win10 VirtualBox VM, and after installing the guest additions, the interface looks like this:

![Screenshot from 2019-03-27 11-33-06](https://user-images.githubusercontent.com/11613312/55069391-3a910b00-5084-11e9-8564-dc9951d5e2f3.png)

So I can't read anything. What could this be caused by?

**Comment by themightyoarfish** [comment]
Update: This really only happens after installing the Oracle video driver. Rolling back the display driver in the device manager removes the problem, but of course also fucks up the resolution.

**Comment by gibbed** [comment]
This is pretty weird. Does this happen with any other WPF apps or is it the save editor specifically?

**Comment by themightyoarfish** [comment]
What would be an example I could test?

**Comment by gibbed** [comment]
Weird! Does that problem happen with other WPF apps? Or just this one?
