### ISSUE TITLE
Failed to load save:invalid or unsupported version

### ISSUE THREAD

**Issue by kga6500** [gibbed/Gibbed.BorderlandsOz#21]
can't open any previous saves and had to make several new saves to mod a character.
any suggestions on how to solve this problem?
![Untitled](https://user-images.githubusercontent.com/49690015/56226543-1f5e5d80-607c-11e9-8b3e-5d74955ab9f4.png)

**Comment by gibbed** [comment]
If you're absolutely sure you're using [the latest version](https://github.com/gibbed/Gibbed.BorderlandsOz/releases/latest), attach samples of saves you cannot load here.
