### ISSUE TITLE
Concerning NDesk.Options Key Value paired arguments

### ISSUE THREAD

**Issue by mwpowellhtx** [gibbed/Gibbed.BorderlandsOz#23]
Hello, and so sorry to post in [this forum](/gibbed/NDesk.Options), but there is literally no way to contact you otherwise that I could find. What is the value of providing a [key/value paired](/gibbed/NDesk.Options/blob/vs2017/Options.cs#L691) action that is not already a [System.String](http://docs.microsoft.com/en-us/dotnet/api/system.string)? i.e. that is, informed by the *option name* itself? Can you show that via an [OptionSet](/gibbed/NDesk.Options/blob/vs2017/Options.cs#L503) [initializer example](http://www.ndesk.org/Options), for instance, please? Cheers, and again, apologies for the cross-post.

**Comment by gibbed** [comment]
I couldn't tell you! I am not the author of NDesk.Options, I merely mirrored it to GitHub since I use it in many of my own projects.

I've never given much thought to how NDesk.Options is implemented outside of how I've always used it.

**Comment by gibbed** [comment]
I also went ahead and enabled issues for my own code, but as I've stated, not the original author.
