### ISSUE TITLE
Feature Request: Save As and make save button save current file.

### ISSUE THREAD

**Issue by ensiform** [gibbed/Gibbed.BorderlandsOz#24]
Any possibility of splitting the save function like any old document editor does? (Save + Save As...)

Save of a new save would still be save as, but if it was a loaded file it would be nice if it remembered the filename so you don't accidentally overwrite a different one. This hasn't happened to me but just in case...

**Comment by gibbed** [comment]
Added as of 43ee6beb44b60656e8722c18ebe735e8a2607a26.
