### ISSUE TITLE
Claptastic Voyage DLC is listed as Marigold Package Def

### ISSUE THREAD

**Issue by ensiform** [gibbed/Gibbed.BorderlandsOz#25]
The other DLCs in 2 and TPS show up properly as their common name in the editor so I would think this should also be the case?

https://github.com/gibbed/Gibbed.BorderlandsOz/blob/master/projects/Gibbed.BorderlandsOz.GameInfo/Resources/Downloadable%20Packages.json#L15

```json
"GD_MarigoldPackageDef.PackageDef_Marigold": {
    "id": 5,
    "dlc_name": "Marigold",
    "display_name": "Marigold Package Def"
  },
```

**Comment by gibbed** [comment]
Fixed as of https://github.com/gibbed/Gibbed.BorderlandsOz/commit/fbc57dc3fdcceef094caf1c5bacd95402d93ea74.
