### ISSUE TITLE
Version 1.0.8 cannot edit missions

### ISSUE THREAD

**Issue by mhartgring** [gibbed/Gibbed.BorderlandsOz#26]
What I did:

* Open savegame
* Go to Raw
* Click on MissionPlaythroughs
* Editor crashes. No warnings, no messages.

Tested with both saeedit and all_tools, with and without symbols.
Tested with an older savegame (2014), a current savegame and with a freshly created character (in game ofcourse).

Editing still works fine with an older version I had laying around: [DEBUG] (7214b51 @ 1-11-2017 02:10).

If you can supply some instructions I'd be willing to help with debugging further.

**Comment by gibbed** [comment]
Fixed with https://github.com/gibbed/Gibbed.BorderlandsOz/commit/914749fc90b3e13be117d1f4c6b17069b6edabf8.
