### ISSUE TITLE
Failed to load save: invalid SHA1 hash

### ISSUE THREAD

**Issue by giddyupah** [gibbed/Gibbed.BorderlandsOz#3]
I've tried everything I've read online but can't avoid this error when trying to open a save including making sure I choose PS3 file, running with admin, etc
Environment: PS3
Character: level 37 baroness
I'm attaching files if that helps.
Thanks for any help you can provide!

[BLUS31445-SAVE-SAVE0001 - Copy.zip](https://github.com/gibbed/Gibbed.BorderlandsOz/files/1443709/BLUS31445-SAVE-SAVE0001.-.Copy.zip)

**Comment by gibbed** [comment]
Did you decrypt the save file? The save editor does not handle PS3 encryption/decryption, you will have to find another tool to do that.

**Comment by giddyupah** [comment]
Yes, with Bruteforce.  I've been using these 2 tools for modding BL2 for over a couple years so I'm familiar with the basics.

**Comment by gibbed** [comment]
I can tell you without a doubt this file isn't a valid save file, so I would however you decrypted it was incorrect, then.

**Comment by giddyupah** [comment]
Do you recommend a good decrypter other than Bruteforce?

**Comment by gibbed** [comment]
I haven't used any tools for it, so I don't know. Perhaps you could check if your settings for the game are correct?

**Comment by giddyupah** [comment]
Thanks for your help and direction.  Based on your previous comment, I went and found a newer version of Bruteforce and it did the trick!

**Comment by gibbed** [comment]
Great!
