### ISSUE TITLE
Crash On Start

### ISSUE THREAD

**Issue by AGlowingThing** [gibbed/Gibbed.BorderlandsOz#6]
Produces a windows application has stopped working error with the following details.

Description
Faulting Application Path:	C:\Users\NA\Downloads\borderlandsoz-1.0.2-with-symbols\bin\Gibbed.BorderlandsOz.SaveEdit.exe

Problem signature
Problem Event Name:	BEX64
Application Name:	Gibbed.BorderlandsOz.SaveEdit.exe
Application Version:	1.0.0.0
Application Timestamp:	59f91f92
Fault Module Name:	d3d9.dll
Fault Module Version:	10.0.16299.98
Fault Module Timestamp:	bc4a6017
Exception Offset:	0000000000043577
Exception Code:	c0000409
Exception Data:	0000000000000002
OS Version:	10.0.16299.2.0.0.256.48
Locale ID:	4105
Additional Information 1:	5d17
Additional Information 2:	5d1724dc9ddec544ec1b16c70350f5d1
Additional Information 3:	27b7
Additional Information 4:	27b746aee2af4642e75e3caf7215562f

Extra information about the problem
Bucket ID:	77d0eb7a09d6b9627c4807bb7a13aff5 (2037887333173538805)

**Comment by gibbed** [comment]
Crash in d3d9? completely unrelated to the save editor, but do you happen to have any software overlays running? Like Discord, etc?

**Comment by AGlowingThing** [comment]
i do have afterburner/rivatuner running, but i used older versions of the save editor without experiencing problems with the OSD

**Comment by gibbed** [comment]
Could you disable those and see if the problem stops occurring, to confirm if that is in fact the issue?

**Comment by AGlowingThing** [comment]
It is the issue. 

Making a profile for the editor in the OSD ordering it not to overlay does allow the OSD to work on other apps while the editor is opened.

Thank you.

Is it possible to prevent such crashes so we don't have to change settings of the OSD?

**Comment by gibbed** [comment]
I'll have to investigate what the problem could be, I'm not touching D3D directly, it's indirect via WPF.

**Comment by AGlowingThing** [comment]
After using other games/apps it is definitely nothing to do with your app. Several other apps and games have new crashes relating to OSDs after the windows full screen optimization update(changes were made to OS interactions with DirectX). Disabling OSDs has resolved all the problems i have been having recently.
