### ISSUE TITLE
Fully Decrypted Files

### ISSUE THREAD

**Issue by Windgale** [gibbed/Gibbed.BorderlandsOz#8]
Hi, I happen to have a program that supposedly fully decrypts the save file, both console encryption and Gearbox's encryption so that it is RAW.  Is it possible to make the editor work with said file if I send it to you?

[Save0002.zip](https://github.com/gibbed/Gibbed.BorderlandsOz/files/1791422/Save0002.zip)

Thanks for taking time to look into it!

**Comment by gibbed** [comment]
Sorry, this won't be implemented because the save editor then would not be able to guarantee the integrity of a save file.

Please ask the developers of that program to provide a proper copy of the save file.

**Comment by Windgale** [comment]
Dang. Oh well, I appreciate the timely response. It is actually for the PS4 version of the game. FYI, if a program ever comes along, or if you end up doing it, the NVIDIA Shield save option works with the normal save after the PS4 encryption is removed.

Thanks!
